### ISSUE TITLE
Start of first Mission Tank not destroyed by missile

### ISSUE THREAD

**Issue by DoubleAgentDave** [yquake2/zaero#15]
The initial section of the first mission has the tank destroyed by a large missile. The missile drops but misses the tank. This occurs on Arch Linux 64 bit and on RPi3 armv7. Really not sure what's going on here. The missile shit is visible here https://youtu.be/PexojVUPOc8?t=159
This issue does not seem to be a problem if compiled on Windows.

**Comment by VortexAcherontic** [comment]
Can confirm the same issue on openSUSE Tumbleweed using the latest source build from 14th Jan 2021.

**Comment by VortexAcherontic** [comment]
Created a pull request #23 which, as soon as merged, will also address this issue :)

**Comment by aianson** [comment]
> Created a pull request #23 which, as soon as merged, will also address this issue :)

I'm looking forward to that. Once I see the pull has been merged I'll grab it and give it a try.. :)

**Comment by Yamagi** [comment]
I've merged the pull request
