### ISSUE TITLE
Missing one enemy in the following levels

### ISSUE THREAD

**Issue by Froyd1** [yquake2/zaero#17]
Just finished playing this awesome mod and want to point out, that I can't get the "listentities monsters" command to work, so I can pin point the missing enemies locations. If someone knows how to turn it on, please tell me and I will post the class name and coordinates of the remaining enemies. They are missing in:

UNIT 2

Administration Center

Kills 80/81

![20210401145927_1](https://user-images.githubusercontent.com/80136749/113438896-5d0a3d00-939e-11eb-813c-6cdf24ac887c.jpg)

UNIT 3

Pipeline Junction

Kills 44/45

![20210401185435_1](https://user-images.githubusercontent.com/80136749/113439113-bffbd400-939e-11eb-8004-1e74e395c1cd.jpg)

**Comment by NeonKnightOA** [comment]
Actually we need to turn zaero into a patch (by diffing it with id's own q2 code) and manually add the content of the patch into yq2 so all the yq2 fixes can apply in zaero as well, this including listentities monsters.

**Comment by Froyd1** [comment]
I totally agree, so that way I can locate the missing enemies, and post they're coordinates. Have @BjossiAlfreds fix the problem, like he did with the expansions, and it should be good.

**Comment by NeonKnightOA** [comment]
It's more complicated than that. Zaero is based on the closed-source Q2 SDK, whose license clashes with YQ2's GPL (the same one used by the released source code by Id Software). We cannot just do that. Yamagi explains it better than me [here](https://github.com/yquake2/3zb2/issues/4).

**Comment by BjossiAlfreds** [comment]
I found and (hopefully) fixed these map bugs, and I (or rather my code) an extra one in zwaste1 and 2 within ztomb3 on Hard/Nightmare. All cases were targetnames that were never targeted. I'm not at all familiar with Zaero's campaign so I only guessed likely targetnames based on context and other triggered monsters. As always I detailed my changes in the comment at the top of each file.
[zaero-mapfixes.zip](https://github.com/yquake2/zaero/files/6251708/zaero-mapfixes.zip)

**Comment by Yamagi** [comment]
> Zaero is based on the closed-source Q2 SDK, whose license clashes with YQ2's GPL (the same one used by the released source code by Id Software).

It might be better / safer to merge from the xatrix addon and not from YQ2. xatrix is essentially baseq2 with some new monsters and other entities. It's licensed under the same crappy SDK license than zaero, @DanielGibson and me have merged nearly all our baseq2 changes to it and we've requested permission from most third party contributors to merge their changes.

**Comment by BjossiAlfreds** [comment]
You guys are welcome to use all of my additions/fixes in zaero. I'd be surprised if anyone was against that, to be honest. Zaero isn't great (in my opinion of course) but it's part of the Quake 2 family.

**Comment by Yamagi** [comment]
I've merged the entity files.
