### ISSUE TITLE
Unable to compile (mingw32)

### ISSUE THREAD

**Issue by NightFright2k19** [yquake2/zaero#27]
During compilation with mingw32, I get this error:

**===> CC src/savegame/savegame.c
src/savegame/savegame.c:65:2: error: #error YQ2OSTYPE should be defined by the build system
   65 | #error YQ2OSTYPE should be defined by the build system
      |  ^~~~~
src/savegame/savegame.c:69:2: error: #error YQ2ARCH should be defined by the build system
   69 | #error YQ2ARCH should be defined by the build system
      |  ^~~~~
src/savegame/savegame.c: In function 'WriteGame':
src/savegame/savegame.c:772:19: error: 'YQ2OSTYPE' undeclared (first use in this function)
  772 |  Q_strlcpy(sv.os, YQ2OSTYPE, sizeof(sv.os) - 1);
      |                   ^~~~~~~~~
src/savegame/savegame.c:772:19: note: each undeclared identifier is reported only once for each function it appears in
src/savegame/savegame.c:773:21: error: 'YQ2ARCH' undeclared (first use in this function)
  773 |  Q_strlcpy(sv.arch, YQ2ARCH, sizeof(sv.arch));
      |                     ^~~~~~~
src/savegame/savegame.c: In function 'ReadGame':
src/savegame/savegame.c:875:26: error: 'YQ2OSTYPE' undeclared (first use in this function)
  875 |   else if (strcmp(sv.os, YQ2OSTYPE) != 0)
      |                          ^~~~~~~~~
src/savegame/savegame.c:880:28: error: 'YQ2ARCH' undeclared (first use in this function)
  880 |   else if (strcmp(sv.arch, YQ2ARCH) != 0)
      |                            ^~~~~~~
make[1]: *** [Makefile:170: build/src/savegame/savegame.o] Error 1
make[1]: Leaving directory '/home/night/zaero-master'
make: *** [Makefile:165: zaero] Error 2**

**Comment by NeonKnightOA** [comment]
Watching at the current Makefile I guess where the error is located:

For example, these lines:

> # Detect the OS
> ifdef SystemRoot
> YQ2_OSTYPE := Windows
> else
> YQ2_OSTYPE := $(shell uname -s)
> endif

Should be...

> # Detect the OS
> ifdef SystemRoot
> YQ2OSTYPE := Windows
> else
> YQ2OSTYPE := $(shell uname -s)
> endif

**Comment by NightFright2k19** [comment]
Incredible, after more than two years a miracle is happening after all! Thanks, guys!
