### ISSUE TITLE
Resolve issues found by PVS

### ISSUE THREAD

**Issue by demoth** [yquake2/zaero#6]
Hi

I have run PVS against the code. Attaching the report.

https://docs.google.com/spreadsheets/d/1GvKCKOQFgO3_1mEUbnznCKxDjcbMK8lOfJWd33EUEck/edit?usp=sharing

**Comment by NeonKnightOA** [comment]
Once I get some time, I'll try to tackle those.

**Comment by NeonKnightOA** [comment]
I saw most of the problems could be solved by just adding an edict sanity check at the beginning of each function that calls one. This has been done in vanilla yq2 and the expansion packs, so it makes sense that it should also be done here.

**Comment by NeonKnightOA** [comment]
Done @demoth . #9 should solve almost all of the issues of that list. Whenever @Yamagi decides so, this commit will be part of the repo.

**Comment by Yamagi** [comment]
I have just merged the PR.
